### ISSUE TITLE
Can this template be used in Overleaf?

### ISSUE THREAD

**Issue by weaverbel** [paultcochrane/uqthesis#1] opened 2017-02-15 01:18 UTC
Hi @paultcochrane 
I am interested in writing my thesis in LaTeX using Overleaf but wondered if these files could be taken into Overleaf to set up the appropriate UQ template. I do not have LaTeX natively installed on any of my computers and was planning to use Overleaf to produce the thesis. I am doing an MPhil and want to get away from Word. 
Thanks !
Overleaf is a tool for writing LaTeX collaboratively in the cloud in case you don't know it. It is online at https://www.overleaf.com/

**Comment by weaverbel** [comment] 2017-02-15 04:05
Hi again @paultcochrane I have found the thesis template in Overleaf ! Now I just have a question of how I change 'department' to 'school'? I tried editing the template in my project but got an error.

**Comment by paultcochrane** [comment] 2017-03-04 21:10
Hi @weaverbel!  My apologies for my late reply: had a lot on at work...  A quick fix would be to change the "Department of" text in `uqthesis.cls` to "School of", however I guess that's probably the change you made.  What error are you getting?  Could you paste the error output into a comment here?  I might be able to see what the problem is (although, I've never used Overleaf, so I might not be of much help).

**Comment by weaverbel** [comment] 2017-03-07 02:04
Thanks @paultcochrane - that worked! I guess someone - not you - put your thesis template into Overleaf and it hasn't been updated for School. Anyway, that worked for me and it looks good now. I don't know LaTeX but I am keen to try using Overleaf as I just hate Word so much ! Overleaf is good - you can write LaTeX easily and submit to journals etc and collaborate with others and so on. Great tool. It's at overleaf.com

**Comment by paultcochrane** [comment] 2017-03-07 12:52
Hi @weaverbel, great to hear that it worked!  I've just pushed a new version of the `uqthesis.cls` which now contains an optional `\school{}` command, so that now one can use either `\department{}` or `\school{}` (or both, if ncessary).  This hopefully makes things a bit easier for people.

Since things work for you now, I'm going to close this issue.  If you have any further problems, please open a new issue.

**Closed as completed by paultcochrane** 2017-03-07 12:52 UTC
